# Generated by Django 3.0.3 on 2020-08-09 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_name', models.CharField(max_length=10, null=True)),
                ('mem_nickname', models.CharField(max_length=10, null=True)),
                ('mem_email', models.EmailField(max_length=254, null=True)),
                ('mem_phone', models.CharField(max_length=25, null=True)),
                ('mem_address', models.CharField(max_length=50, null=True)),
                ('like_post', models.ManyToManyField(blank=True, related_name='like_user', to='main.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
